import sys, time, math
from tppflush import *
serverIP = input("Enter your IP: ")
#serverIP=sys.argv[1]
server=LumaInputServer(serverIP)
#server=serverIP
x=0
time.sleep(4)
while True:
    server.press(HIDButtons.L)
    server.send(print_sent=False)
    server.press(HIDButtons.R)
    server.send(print_sent=False)
    time.sleep(0.2)
    server.press(HIDButtons.START)
    server.send(print_sent=False)
    server.press(HIDButtons.SELECT)
    server.send(print_sent=False)
    time.sleep(0.3)
    server.unpress(HIDButtons.L)
    server.send(print_sent=False)
    server.unpress(HIDButtons.R)
    server.send(print_sent=False)
    time.sleep(0.2)
    server.clear_everything()
    server.send(print_sent=False)
    print('Soft reset.')

    x+=1
    print('\nAttempt #'+str(x))
    time.sleep(18)
    print('Part 1: Intro animation')
    server.press(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.5)
    server.unpress(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.1)

    time.sleep(3)
    print('Part 2: Title screen')
    server.press(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.5)
    server.unpress(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.1)

    time.sleep(5)
    print('Part 3: Menu selection')
    server.press(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.5)
    server.unpress(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.1)

    time.sleep(3)
    print('Part 4: Comm. error wtf')
    server.press(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.5)
    server.unpress(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.1)

    time.sleep(3)
    print('Part 5: Ballsack')
    server.press(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.5)
    server.unpress(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.1)

    time.sleep(4.5)
    print('Part 6: Gex is calling')
    print('        First press')
    server.touch(90,120)
    server.send(print_sent=False)
    time.sleep(1)
    server.clear_touch()
    server.send(print_sent=False)
    time.sleep(1)
    print('        Second press')
    server.touch(90,120)
    server.send(print_sent=False)
    time.sleep(1)
    server.clear_touch()
    server.send(print_sent=False)
    time.sleep(1)

    '''
    server.press(HIDButtons.DPADLEFT)
    server.send(print_sent=False)
    time.sleep(0.5)
    server.unpress(HIDButtons.DPADLEFT)
    server.send(print_sent=False)
    time.sleep(0.1)
    print('        Second press')
    server.press(HIDButtons.DPADLEFT)
    server.send(print_sent=False)
    time.sleep(0.4)
    server.unpress(HIDButtons.DPADLEFT)
    server.send(print_sent=False)
    time.sleep(1)
    '''

    print('        Third press')
    server.press(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.5)
    server.unpress(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(1)
    print('        Fourth press')
    server.press(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.5)
    server.unpress(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.1)
    print('        Fifth for good measure')
    server.press(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.5)
    server.unpress(HIDButtons.A)
    server.send(print_sent=False)
    time.sleep(0.1)

    print('Part 7: The Encounter')
    time.sleep(13)
    print('Resetting in 5...')
    time.sleep(1)
    print('Resetting in 4...')
    time.sleep(1)
    print('Resetting in 3...')
    time.sleep(1)
    print('Resetting in 2...')
    time.sleep(1)
    print('Resetting in 1...')
    time.sleep(1)
